{% set version = '2.0' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rsqlite
  version: {{ version|replace("-", "_") }}

source:
  fn: RSQLite_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/RSQLite_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/RSQLite/RSQLite_{{ version }}.tar.gz
  sha256: 7f0fe629f34641c6af1e8a34412f3089ee2d184853843209d97ffe29430ceff6

build:
  merge_build_host: True  # [win]
  number: 1
  skip: true  # [win32]

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - posix                # [win]
    - {{ compiler('c') }}        # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ compiler('cxx') }}        # [unix]
    - {{ compiler('m2w64_cxx') }}  # [win]
  host:
    - r-base
    - r-bh
    - r-dbi >=0.4_9
    - r-rcpp >=0.12.7
    - r-memoise
    - r-plogr
    - r-bit64
    - r-blob
    - r-pkgconfig

  run:
    - r-base
    - r-bh
    - r-dbi >=0.4_9
    - r-rcpp >=0.12.7
    - r-memoise
    - r-plogr
    - r-bit64
    - r-blob
    - r-pkgconfig

test:
  commands:
    - $R -e "library('RSQLite')"  # [not win]
    - "\"%R%\" -e \"library('RSQLite')\""  # [win]

about:
  home: https://github.com/rstats-db/RSQLite
  license: LGPL (>= 2)
  summary: Embeds the 'SQLite' database engine in R and provides an interface compliant with
    the 'DBI' package. The source for the 'SQLite' engine (version 3.8.8.2) is included.
  license_family: LGPL

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
